# Generated by Django 4.2.11 on 2024-04-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_freelancer',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('is_freelancer', 'Фрилансер'), ('is_customer', 'Клиент')], default='is_freelancer'),
        ),
    ]
