# Generated by Django 4.2.11 on 2024-04-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_customer_remove_user_is_freelancer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('is_freelancer', 'Фрилансер'), ('is_customer', 'Клиент')], default='is_freelancer', max_length=20),
        ),
    ]
