# Generated by Django 4.2.11 on 2024-04-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_customuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('freelancer', 'Фрилансер'), ('customer', 'Клиент')], default='1', max_length=20),
        ),
    ]
