version: '3.8'

services:
  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/freelance_django/
    env_file:
      - .env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15-alpine
    env_file:
      - .env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

#  nginx:
#    build: ./nginx
#    volumes:
#      - static:/static
#    ports:
#      - "80:80"
#    depends_on:
#      web:
#        condition: service_healthy


volumes:
  postgres_data: