FROM python:3.10-alpine

WORKDIR /usr/src/app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r /usr/src/app/requirements.txt

COPY ./entrypoint.prod.sh /usr/src/app/entrypoint.prod.sh

COPY . /usr/src/app/

ENTRYPOINT ["/usr/src/app/entrypoint.prod.sh"]